"use client";

import { Inter } from "next/font/google";
import Footer from "../components/Footer";
import Header from "../components/Header";
import "./styles/globals.scss";
import ReactQueryProvider from "./ReactQueryProvider";

import { ThemeProvider } from "@material-tailwind/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <ThemeProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ThemeProvider>
    </ReactQueryProvider>
  );
}
