"use client";

import { Inter } from "next/font/google";
import ReactQueryProvider from "./ReactQueryProvider";
import "./styles/globals.scss";

import { ThemeProvider } from "@material-tailwind/react";
import { ReduxProviders } from "./ReduxProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProviders>
      <ReactQueryProvider>
        <ThemeProvider>
          <html lang="en">
            <body className={inter.className}>{children}</body>
          </html>
        </ThemeProvider>
      </ReactQueryProvider>
    </ReduxProviders>
  );
}
