"use client";
import { ThemeProvider } from "@material-tailwind/react";
import { Inter } from "next/font/google";
import ReactQueryProvider from "./ReactQueryProvider";
import { ReduxProviders } from "./ReduxProvider";
import "./styles/globals.scss";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProviders>
      <ReactQueryProvider>
        <ThemeProvider>
          <html lang="en">
            <body className={inter.className}>
              {children}
              <ToastContainer />
            </body>
          </html>
        </ThemeProvider>
      </ReactQueryProvider>
    </ReduxProviders>
  );
}
